version: '3.9'

services:
  bossabox:
    container_name: bossabox
    image: bossabox
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      #POSTGRES_DB: localstack
    ports:
      - 5432:5432
    
    networks:
      - global-default

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 5050:80
      - 5051:443
    depends_on:
      - postgres

    networks:
      - global-default

networks:
  global-default:
    external: true
